"""wholesale wallet returns tickets

Revision ID: 083a53292656
Revises: 6632d19a5204
Create Date: 2026-09-30 11:43:22.820628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '083a53292656'
down_revision: Union[str, None] = '6632d19a5204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Allow the existing 'user_role' enum to accept the new 'WHOLESALE' member.
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'WHOLESALE'")

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('tx_type', sa.Enum('TOPUP', 'DEDUCT', 'REFUND', 'ORDER_PAYMENT', name='wallet_tx_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('WRONG_SIZE', 'DEFECTIVE', 'NOT_AS_DESCRIBED', 'CHANGED_MIND', 'OTHER', name='return_reason'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='return_status'), nullable=False),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    postgresql.ENUM('RETAIL', 'WHOLESALE', name='order_type').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='wholesale_status').create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('order_type', sa.Enum('RETAIL', 'WHOLESALE', name='order_type'), nullable=False, server_default='RETAIL'))
    op.add_column('orders', sa.Column('is_manual', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('orders', sa.Column('shipping_provider', sa.String(length=60), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['created_by_id'], ['id'])
    op.add_column('products', sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('wholesale_min_qty', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('wholesale_status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='wholesale_status'), nullable=False, server_default='NONE'))
    op.add_column('users', sa.Column('wholesale_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    op.drop_column('users', 'wholesale_requested_at')
    op.drop_column('users', 'wholesale_status')
    op.drop_column('users', 'company_name')
    op.drop_column('products', 'wholesale_min_qty')
    op.drop_column('products', 'wholesale_price')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'shipping_provider')
    op.drop_column('orders', 'is_manual')
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'created_by_id')
    op.drop_table('return_requests')
    op.drop_table('wallet_transactions')
    op.drop_table('ticket_messages')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
