"""activity log system

Revision ID: 141056ba52ce
Revises: bc8361409780
Create Date: 2026-09-30 14:39:59.021104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '141056ba52ce'
down_revision: Union[str, None] = 'bc8361409780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='log_level'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=150), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_category'), 'activity_logs', ['category'], unique=False)
    op.create_index(op.f('ix_activity_logs_level'), 'activity_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_level'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_category'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
