"""product image color tag

Revision ID: bc8361409780
Revises: 083a53292656
Create Date: 2026-09-30 11:59:11.954746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc8361409780'
down_revision: Union[str, None] = '083a53292656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('color', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'color')
    # ### end Alembic commands ###
